import 'package:flutter/material.dart';
import '../language_notifier.dart'; // Переконайся, що цей шлях правильний

// Словник з усіма текстами
const Map<String, Map<String, String>> localizedStrings = {
  'uk': {
    'portfolioTitle': 'Портфоліо Назарія Лучківа',
    'playerName': 'Назарій Лучків',
    'nav_about': 'Про Мене',
    'nav_projects': 'Проєкти',
    'nav_contacts': 'Контакти',
    'nav_settings': 'Налаштування',
    'play_button': 'PLAY (Classic)',
    'about_title': 'ПРО МЕНЕ:',
    'about_text_p1': 'Привіт! Я Назарій Лучків, мені 15 років. Я навчаюся на професію \'Оператор з обробки інформації та програмного забезпечення\'.',
    'about_text_p2': 'Я люблю грати в ігри та дивитися серіали. Мої улюблені ігри – це Red Dead Redemption 2, The Witcher 3: Wild Hunt та The Last of Us. Із серіалів можу виділити \'Пуститися берега\' (Breaking Bad), \'Краще подзвоніть Солу\' (Better Call Saul) та \'Клан Сопрано\' (The Sopranos).',
    'about_text_p3': 'У майбутньому я планую вивчати програмування.',
    'projects_title': 'МОЇ ПРОЄКТИ:',
    'projects_wip_title': 'ЗАПЛАНОВАНО:',
    'projects_wip_tag': '(В РОЗРОБЦІ)',
    'project_portfolio_title': 'Pixel Portfolio [Minecraft Style]',
    'project_portfolio_desc': 'Моє портфоліо. Цей сайт зроблено на Flutter та натхненно стилем Minecraft.',
    'project_portfolio_tech': 'Технології: Flutter Web, Dart',
    'projects_insta_title': 'Instagram UI Clone',
    'projects_insta_desc': 'Клон інтерфейсу популярної соціальної мережі Instagram, створений для практики навичок UI/UX у Flutter.',
    'projects_insta_tech': 'Технології: Flutter, Dart',
    'github_button': 'GitHub',
    'site_button': 'Сайт',
    'projects_alpha_title': 'Проєкт "Альфа"',
    'projects_alpha_desc': 'Зараз я активно працюю над цією ідеєю. Більше деталей з\'явиться незабаром!',
    'projects_beta_title': 'Проєкт "Бета"',
    'projects_beta_desc': 'Ще один проєкт у процесі розробки. Слідкуйте за оновленнями на моєму GitHub!',
    'contacts_title': 'КОНТАКТИ:',
    'contacts_subtitle': 'ЗАВЖДИ ВІДКРИТИЙ ДО СПІЛКУВАННЯ ТА НОВИХ ІДЕЙ! ЗВ\'ЯЖІТЬСЯ ЗІ МНОЮ:',
    'contact_github': 'GitHub',
    'contact_telegram': 'Telegram',
    'contact_instagram': 'Instagram',
    'contact_email': 'Email',
    'settings_title': 'НАЛАШТУВАННЯ',
    'settings_theme_light': 'Світла тема',
    'settings_lang_switch': 'Переключити на English',
    'settings_lang_current': 'Поточна мова:',
    'error_launch': 'Не вдалося відкрити',
    // Нові ачівки
    'ach_get_title': 'Досягнення здобуто!',
    'ach_first_visit_desc': 'Дослідник Портфоліо!',
    'ach_play_game_desc': 'Час для гри!',
    'ach_view_about_desc': 'Знайомство відбулося!',
    'ach_view_projects_desc': 'Майстер Проєктів',
    'ach_view_contacts_desc': 'На Зв\'язку!',
    'ach_open_github_repo_desc': 'Дослідник Коду!',
    'ach_switch_theme_desc': 'Володар Світла і Темряви!',
    'ach_switch_language_desc': 'Поліглот!',
  },
  'en': {
    'portfolioTitle': 'Nazariy Luchkiv Portfolio',
    'playerName': 'Nazariy Luchkiv',
    'nav_about': 'About Me',
    'nav_projects': 'Projects',
    'nav_contacts': 'Contacts',
    'nav_settings': 'Settings',
    'play_button': 'PLAY (Classic)',
    'about_title': 'ABOUT ME:',
    'about_text_p1': 'Hi! I\'m Nazariy Luchkiv, I\'m 15 years old. I\'m studying to become an Information Processing and Software Operator.',
    'about_text_p2': 'I love playing games and watching series. My favorite games are Red Dead Redemption 2, The Witcher 3: Wild Hunt, and The Last of Us. Among the series, I can highlight Breaking Bad, Better Call Saul, and The Sopranos.',
    'about_text_p3': 'In the future, I plan to study programming.',
    'projects_title': 'MY PROJECTS:',
    'projects_wip_title': 'PLANNED:',
    'projects_wip_tag': '(IN PROGRESS)',
    'project_portfolio_title': 'Pixel Portfolio [Minecraft Style]',
    'project_portfolio_desc': 'My portfolio. This site was built with Flutter and inspired by the Minecraft style.',
    'project_portfolio_tech': 'Technologies: Flutter Web, Dart',
    'projects_insta_title': 'Instagram UI Clone',
    'projects_insta_desc': 'A clone of the popular social network Instagram\'s interface, created to practice UI/UX skills in Flutter.',
    'projects_insta_tech': 'Technologies: Flutter, Dart',
    'github_button': 'GitHub',
    'site_button': 'Website',
    'projects_alpha_title': 'Project "Alpha"',
    'projects_alpha_desc': 'I am currently actively working on this idea. More details will appear soon!',
    'projects_beta_title': 'Project "Beta"',
    'projects_beta_desc': 'Another project in development. Follow updates on my GitHub!',
    'contacts_title': 'CONTACTS:',
    'contacts_subtitle': 'ALWAYS OPEN TO COMMUNICATION AND NEW IDEAS! CONTACT ME:',
    'contact_github': 'GitHub',
    'contact_telegram': 'Telegram',
    'contact_instagram': 'Instagram',
    'contact_email': 'Email',
    'settings_title': 'SETTINGS',
    'settings_theme_light': 'Light Theme',
    'settings_lang_switch': 'Switch to Ukrainian',
    'settings_lang_current': 'Current language:',
    'error_launch': 'Could not launch',
    // New achievements
    'ach_get_title': 'Achievement get!',
    'ach_first_visit_desc': 'Portfolio Explorer!',
    'ach_play_game_desc': 'Time to Play!',
    'ach_view_about_desc': 'Met the Creator!',
    'ach_view_projects_desc': 'Project Artisan',
    'ach_view_contacts_desc': 'Made Contact!',
    'ach_open_github_repo_desc': 'Code Explorer!',
    'ach_switch_theme_desc': 'Master of Light & Shadow!',
    'ach_switch_language_desc': 'Polyglot!',
  },
};

// Функція-перекладач
String tr(BuildContext context, String key) {
  final locale = languageNotifier.value;
  return localizedStrings[locale.languageCode]?[key] ?? key;
}